title: WAMF
description: Wildlife Activity Monitoring Framework
url: "https://wamf.uk"
baseurl: ""

markdown: kramdown

permalink: /blog/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
